blog_comments:
  - comment_id I NOTNULL AUTO PRIMARY
  - post_id I NOTNULL DEFAULT 0
  - body XL NOTNULL
  - created I NOTNULL

blog_posts:
  - post_id I NOTNULL AUTO PRIMARY
  - title C(255) NOTNULL
  - body XL NOTNULL
  - created I NOTNULL
  - updated I NOTNULL
  - comments_count I NOTNULL DEFAULT 0
  - tags_count I NOTNULL DEFAULT 0

blog_posts_has_tags:
  - post_id I NOTNULL PRIMARY
  - tag_id I NOTNULL PRIMARY

blog_tags:
  - tag_id I NOTNULL AUTO PRIMARY
  - label C(64) NOTNULL
